name: open-mmlab/MiniCPM-V
revision: null
dtype: float16
device: cuda
attn_implementation: null
max_sequence_length: 2048
adapter_target: auto
adapter_kwargs:
  vocab_size: 32000
  num_heads: 6
  num_visual_tokens: 48
gpu_id: null
