name: open-mmlab/MiniCPM-V
revision: null
dtype: float16
device: cuda
attn_implementation: null
max_sequence_length: 2048
adapter_target: svlm.model_adapter.MiniCPMVAdapter
adapter_kwargs:
  model_name: open-mmlab/MiniCPM-V
  torch_dtype: float16
  attn_implementation: null
gpu_id: 0
