name: Qwen/Qwen2-VL-2B-Instruct
revision: null
dtype: bfloat16
device: cuda
attn_implementation: null
max_sequence_length: 4096
adapter_target: svlm.model_adapter.Qwen2VLAdapter
adapter_kwargs:
  model_name: Qwen/Qwen2-VL-2B-Instruct
  torch_dtype: bfloat16
  attn_implementation: null
gpu_id: 0
