program: sweep_train.py
project: svlm-calibration
entity: medicalissues
method: bayes  # bayes, grid, or random
metric:
  name: pope_f1
  goal: maximize

parameters:
  # Calibration hyperparameters
  method.lambda_:
    distribution: uniform
    min: 0.05
    max: 0.5

  method.beta:
    distribution: uniform
    min: 0.8
    max: 0.95

  method.alpha:
    distribution: uniform
    min: 0.4
    max: 0.7

  method.ven_eps:
    distribution: log_uniform_values
    min: 1e-6
    max: 1e-3

  # Extreme manipulation modes (categorical choice)
  method.use_contrastive:
    values: [true, false]

  method.use_adversarial:
    values: [true, false]

  method.use_adaptive_temp:
    values: [true, false]

  # Contrastive parameters
  method.contrastive_strength:
    distribution: uniform
    min: 2.0
    max: 20.0

  # Adversarial parameters
  method.adversarial_strength:
    distribution: uniform
    min: 0.1
    max: 1.0

  method.adversarial_iterations:
    values: [1, 2, 3, 4, 5]

  # Adaptive temperature parameters
  method.temp_range:
    distribution: uniform
    min: 1.0
    max: 10.0

  method.temp_visual_boost:
    values: [true, false]

  # Decoding parameters
  decoding.temperature:
    distribution: uniform
    min: 0.3
    max: 0.8

  decoding.top_p:
    distribution: uniform
    min: 0.7
    max: 0.95

  # Fixed parameters (not searched)
  data:
    value: pope_adversarial

  model:
    value: qwen2_vl_2b

  run.run_name:
    value: sweep_run

# Early termination
early_terminate:
  type: hyperband
  min_iter: 3
  eta: 2
  s: 3
