program: sweep_train.py
project: svlm-calibration
entity: medicalissues
method: grid

metric:
  name: pope_f1
  goal: maximize

parameters:
  # Grid search over key hyperparameters
  method.lambda_:
    values: [0.3, 0.5, 0.7, 0.9]

  method.beta:
    values: [0.7, 0.8, 0.9]

  method.alpha:
    values: [0.4, 0.6, 0.8]

  # Extreme manipulation modes
  method.use_contrastive:
    values: [false, true]

  method.use_adversarial:
    values: [false, true]

  method.use_adaptive_temp:
    values: [false, true]

  # Extreme parameters (fewer values for grid search)
  method.contrastive_strength:
    values: [5.0, 10.0, 15.0]

  method.adversarial_strength:
    values: [0.3, 0.5]

  method.adversarial_iterations:
    values: [2, 3]

  method.temp_range:
    values: [3.0, 5.0, 8.0]

  method.temp_visual_boost:
    values: [true, false]

  # Fixed parameters
  data:
    value: pope_adversarial

  model:
    value: qwen2_vl_2b

  method.use_erw:
    value: true

  method.use_pva:
    value: true

  method.use_ven:
    value: true

  decoding.temperature:
    value: 0.7

  decoding.top_p:
    value: 0.9
