program: sweep_train.py
project: svlm-calibration
entity: medicalissues
method: random

metric:
  name: pope_accuracy
  goal: maximize

parameters:
  # Random search - good for quick exploration
  method.lambda_:
    distribution: uniform
    min: 0.1
    max: 10.0

  method.beta:
    distribution: uniform
    min: 0.7
    max: 0.95

  method.alpha:
    distribution: uniform
    min: 0.3
    max: 0.8

  # Auto scaling parameters
  method.auto_scale_lambda:
    values: [true, false]

  method.target_logit_impact:
    distribution: uniform
    min: 0.01
    max: 0.15

  method.max_lambda:
    distribution: uniform
    min: 50.0
    max: 1000.0

  method.min_lambda:
    distribution: log_uniform_values
    min: 0.001
    max: 0.1

  # Fixed parameters
  data:
    value: pope

  model:
    value: qwen2_vl_2b

  method.use_erw:
    value: true

  method.use_pva:
    value: true

  method.use_ven:
    value: false

# Number of runs
count: 30
