program: sweep_train.py
project: svlm-calibration
entity: medicalissues
method: random

metric:
  name: pope_accuracy
  goal: maximize

parameters:
  # Random search - good for quick exploration
  method.lambda_:
    distribution: uniform
    min: 0.2
    max: 1.0

  method.beta:
    distribution: uniform
    min: 0.6
    max: 0.95

  method.alpha:
    distribution: uniform
    min: 0.3
    max: 0.8

  # Extreme manipulation modes (random sampling)
  method.use_contrastive:
    values: [true, false]

  method.use_adversarial:
    values: [true, false]

  method.use_adaptive_temp:
    values: [true, false]

  # Extreme parameters
  method.contrastive_strength:
    distribution: uniform
    min: 1.0
    max: 25.0

  method.adversarial_strength:
    distribution: uniform
    min: 0.05
    max: 1.5

  method.adversarial_iterations:
    values: [1, 2, 3, 4, 5, 6]

  method.temp_range:
    distribution: uniform
    min: 0.5
    max: 12.0

  method.temp_visual_boost:
    values: [true, false]

  # Fixed parameters
  data:
    value: pope

  model:
    value: qwen2_vl_2b

  method.use_erw:
    value: true

  method.use_pva:
    value: true

  method.use_ven:
    value: false

# Number of runs
count: 30
