program: sweep_train.py
project: svlm-calibration
entity: medicalissues
method: grid

metric:
  name: pope_f1
  goal: maximize

parameters:
  # Grid search over key hyperparameters
  method.lambda_:
    values: [0.5, 1.0, 2.0, 5.0]

  method.beta:
    values: [0.8, 0.9, 0.95]

  method.alpha:
    values: [0.4, 0.6, 0.8]

  # Auto scaling parameters
  method.auto_scale_lambda:
    values: [false, true]

  method.target_logit_impact:
    values: [0.02, 0.05, 0.1]

  method.max_lambda:
    values: [100.0, 200.0, 500.0]

  method.min_lambda:
    values: [0.005, 0.01, 0.05]

  # Fixed parameters
  data:
    value: pope_adversarial

  model:
    value: qwen2_vl_2b

  method.use_erw:
    value: true

  method.use_pva:
    value: true

  method.use_ven:
    value: true

  decoding.temperature:
    value: 0.7

  decoding.top_p:
    value: 0.9
